# Generated by Django 5.2 on 2025-04-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_github_profile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
